[package]
name = "arne-leptos"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-timers = { version = "0.3.0", features = ["futures"] }
leptos = { version = "0.8.2", features = ["csr"] }
